name: Cargo Check

on:
  - push
  - pull_request

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain/component(s)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      
      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check